checks:
    php: true
build:
    tests:
        override:
            - phpcs-run
    environment:
        php:
            version: 7.2
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, docs]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, docs]
filter:
    excluded_paths:
        - 'vendor/*'
