<?php
declare(strict_types=1);


namespace DanchukAS\AmadeusTechTask123;


/**
 * Interface IGlobalFunctionLib
 * 
 * Generated by util/ILibGenerator.php automatically.
 * ============ WARNING ==================== 
 * = Not edit manual !                     =
 * = If you want change something          =
 * = create new class and inherit by this. = 
 * =========================================
 *
 * @method createFunctionalObject($class = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateFunctionalObject::run
 * }
 *
 * @method createObject(string $class_name = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateObject::run
 * }
 *
 * @method output($message) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\Output::run
 * }
 *
 * @method buildZoo($animal_collection = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\BuildZoo::run
 * }
 *
 * @method callAction($object, string $action_name, array $action_param = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CallAction::run
 * }
 *
 * @method createAction(\ARunParam $runParam, $class = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateAction::run
 * }
 *
 * @method createAnimal($name, $class = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateAnimal::run
 * }
 *
 * @method createRunParam(string $class = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateRunParam::run
 * }
 *
 * @method createZoo($class = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateZoo::run
 * }
 *
 * @method getAbilityForAction($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetAbilityForAction::run
 * }
 *
 * @method getActionClass($action, $object = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionClass::run
 * }
 *
 * @method string getActionClassName($object, $action_method_name) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionClassName::run
 * }
 *
 * @method getActionLib() {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionLib::run
 * }
 *
 * @method string getActionMethodName($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionMethodName::run
 * }
 *
 * @method array getAnimalCollection(\IHasAnimalCollection $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetAnimalCollection::run
 * }
 *
 * @method getLifeCycle(\IHasLifeCycle $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetLifeCycle::run
 * }
 *
 * @method getName(\IHasName $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetName::run
 * }
 *
 * @method getRunParam(\IHasRunParam $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetRunParam::run
 * }
 *
 * @method initAmadeusZooAnimalCollection() {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\InitAmadeusZooAnimalCollection::run
 * }
 *
 * @method isAvailableActionRun($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\IsAvailableActionRun::run
 * }
 *
 * @method live($object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\Live::run
 * }
 *
 * @method mergeRunParam(\IHasRunParam $object, \ARunParam ...$additionRunParam) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\MergeRunParam::run
 * }
 *
 * @method runAction(AAction $action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\RunAction::run
 * }
 *
 * @method void runNewAction($action_class, $run_param) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\RunNewAction::run
 * }
 *
 * @method setAnimalCollection(\IHasAnimalCollection $object, $collection) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetAnimalCollection::run
 * }
 *
 * @method setLib($object, $lib) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetLib::run
 * }
 *
 * @method setName(\IHasName $object, $name) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetName::run
 * }
 *
 * @method setObject(\IHasObject $object, $propertyObject) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetObject::run
 * }
 *
 * @method setRunParam(\IHasRunParam $object, \ARunParam $runParam) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetRunParam::run
 * }
 */
interface IGlobalFunctionLib
{ 

}
