<?php
declare(strict_types=1);


namespace DanchukAS\AmadeusTechTask123;


/**
 * Interface IGlobalFunctionLib
 *
 * Generated by util/ILibGenerator.php automatically.
 * ============ WARNING ====================
 * = Not edit manual !                     =
 * = If you want change something          =
 * = create new class and inherit by this. =
 * =========================================
 *
 * @method callAction($object, string $action_name, array $action_param = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CallAction::run
 * }
 *
 * @method createAnimal($name, $class = \Animal::class) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\CreateAnimal::run
 * }
 *
 * @method getAbilityForAction($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetAbilityForAction::run
 * }
 *
 * @method getActionClass($action, $object = null) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionClass::run
 * }
 *
 * @method string getActionClassName($object, $action_method_name) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionClassName::run
 * }
 *
 * @method getActionLib() {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionLib::run
 * }
 *
 * @method string getActionMethodName($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetActionMethodName::run
 * }
 *
 * @method array getAnimalCollection(\IHasAnimalCollection $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetAnimalCollection::run
 * }
 *
 * @method getLifeCycle(\IHasLifeCycle $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetLifeCycle::run
 * }
 *
 * @method getName(\IHasName $object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\GetName::run
 * }
 *
 * @method initAmadeusZooAnimalCollection() {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\InitAmadeusZooAnimalCollection::run
 * }
 *
 * @method isAvailableActionRun($action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\IsAvailableActionRun::run
 * }
 *
 * @method live($object) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\Live::run
 * }
 *
 * @method runAction(AAction $action) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\RunAction::run
 * }
 *
 * @method void runNewAction($action_class, $run_param) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\RunNewAction::run
 * }
 *
 * @method setAnimalCollection(\IHasAnimalCollection $object, $collection) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetAnimalCollection::run
 * }
 *
 * @method setLib($object, $lib) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetLib::run
 * }
 *
 * @method setName(\IHasName $object, $name) {
 * @see \DanchukAS\AmadeusTechTask123\GlobalFunctionLib\SetName::run
 * }
 */
interface IGlobalFunctionLib
{

}
