<?php
declare(strict_types=1);


namespace DanchukAS\AmadeusTechTask123\ILib;


/**
 * Interface IAction
 *
 * Generated by util/ILibGenerator.php automatically.
 * ============ WARNING ====================
 * = Not edit manual !                     =
 * = If you want change something          =
 * = create new class and inherit by this. =
 * =========================================
 *
 * @method output($action) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Action\Output::run
 * }
 *
 * @method undefinedAction(AAction $action) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Action\UndefinedAction::run
 * }
 *
 * @method walk(AAction $action) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Action\Walk::run
 * }
 */
interface IAction
{

}
