<?php
declare(strict_types=1);


namespace DanchukAS\AmadeusTechTask123\ILib;


/**
 * Interface IBase
 * 
 * Generated by util/ILibGenerator.php automatically.
 * ============ WARNING ==================== 
 * = Not edit manual !                     =
 * = If you want change something          =
 * = create new class and inherit by this. = 
 * =========================================
 *
 * @method createFunctionalObject($class = null) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Base\CreateFunctionalObject::run
 * }
 *
 * @method createObject(string $class_name = null) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Base\CreateObject::run
 * }
 *
 * @method output($message) {
 * @see \DanchukAS\AmadeusTechTask123\Lib\Base\Output::run
 * }
 */
interface IBase
{ 

}
