<?php
declare(strict_types=1);


namespace DanchukAS\AmadeusTechTask123;


/**
 * Interface IActionFunctionLib
 * 
 * Generated by util/ILibGenerator.php automatically.
 * ============ WARNING ==================== 
 * = Not edit manual !                     =
 * = If you want change something          =
 * = see implementation in /src/ActionFunction/ActionFunctionLib.php = 
 * =========================================
 *
 * @method output($action) {
 * @uses \DanchukAS\AmadeusTechTask123\ActionFunctionLib\Output::run
 * }
 *
 * @method undefinedAction(AAction $action) {
 * @uses \DanchukAS\AmadeusTechTask123\ActionFunctionLib\UndefinedAction::run
 * }
 *
 * @method walk(AAction $action) {
 * @uses \DanchukAS\AmadeusTechTask123\ActionFunctionLib\Walk::run
 * }
 */
interface IActionFunctionLib
{ 

}
